name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: sisques-labs/workflows/.github/actions/setup@main
        with:
          node_version: "24"

      - name: Install dependencies
        uses: sisques-labs/workflows/.github/actions/install@main

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
