name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version bump type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      release_type:
        description: Release type
        required: true
        type: choice
        default: stable
        options:
          - stable
          - alpha
          - beta

jobs:
  release:
    uses: sisques-labs/workflows/.github/workflows/docker-release.yml@main
    with:
      image_name: sisqueslabs/${{ github.event.repository.name }}
      version: ${{ inputs.version }}
      release_type: ${{ inputs.release_type }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
